module.exports={
    btnAddUser: '.orangehrm-header-container > .oxd-button',
    btnAddJob: '.oxd-button',
    fieldUsernameSearchUser: ':nth-child(2) > .oxd-input',
    existingUsernameElement: "//div[contains(text(),'jdoe123')]",
    userRowElement: "//div[@class='oxd-table-card']//div[@role='row']",
    btnSearch: '.oxd-form-actions > .oxd-button--secondary',
    selectStatusSearchUser: ':nth-child(4) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon',
    userRoleSelect: ':nth-child(4) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input',
    selectDropdown: '.oxd-select-dropdown',
    optionEnabled: '.oxd-select-text-input',
    tableRow: '.oxd-table-row',
    usernameTableCell: '.oxd-table-card > .oxd-table-row',
    iconDelete: '.oxd-table-cell-actions > :nth-child(1) > .oxd-icon',
    confirmDeleteData: '.oxd-button--label-danger',
    errorMessage: '.oxd-input-group > .oxd-text',
    jobMenu: '.oxd-topbar-body-nav > ul > :nth-child(2)',
    jobDropdown: '.oxd-topbar-body-nav-tab-link',
    employeeDropdown: '.oxd-autocomplete-option'
}